### ISSUE TITLE
StarUsbCashDrawer NuGet Link

### ISSUE THREAD

**Issue by jonmpoole80** [star-micronics/starlabs-cashdrawer-sdk-windows#1]
<package id="StarUsbCashDrawer" version="1.0.0" targetFramework="net45" />
This link is not available via NuGet, How can I get this as without it this project is not usable

**Comment by gare-bear** [comment]
@jonmpoole80 We won't be pushing to NuGet for the time being but if you're still interested I can create a local Nuget Package for you from source.
